spring.application.name=demo
spring.datasource.url=jdbc:mysql://localhost:3306/swim_app
spring.datasource.username=root
spring.datasource.password=你的密码

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true